# Generated by Django 3.1.4 on 2022-10-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kotxea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255)),
                ('precioHora', models.FloatField()),
                ('alokatzeData', models.DateField()),
            ],
        ),
    ]
